[workspace]
channels = ["conda-forge"]
name = "ai-demos"
platforms = ["linux-64", "linux-aarch64", "osx-arm64"]
version = "0.1.0"
description = "Conda packages for AI demos hosted on prefix.dev/ai-demos"

[tasks]
check = { depends-on = ["test-workflow"] }
build-new = "rattler-build build -c https://prefix.dev/ai-demos -c conda-forge --recipe-dir recipes/ --skip-existing=all --no-test"
build-all = "rattler-build build -c https://prefix.dev/ai-demos -c conda-forge --recipe-dir recipes/ --no-test"
ci-build = "rattler-build build -c ./output -c https://prefix.dev/ai-demos -c conda-forge --recipe-dir recipes/ --variant-config conda_build_config.yaml --skip-existing=all --no-test --continue-on-failure --target-platform=$TARGET_PLATFORM --noarch-build-platform=linux-64"
ci-build-beszel-windows = "rattler-build build -c https://prefix.dev/ai-demos -c conda-forge --recipe recipes/beszel-agent/recipe.yaml --target-platform=win-64 --skip-existing=all --no-test"
update-npm = "python .github/scripts/update-npm.py"
test-workflow = "python -m unittest discover tests"

[dependencies]
rattler-build = ">=0.58.4,<0.59"
python = "3.13.*"
pyyaml = "6.0.*"
