context:
  version: "0.1.19"

package:
  name: playwright-cli
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/@playwright/cli/-/cli-${{ version }}.tgz
  sha256: 0a6fca06371fa7e69be33f6730f78d7bdd69d037390045c4050e961e8b1dfeee

build:
  number: 0
  script: build.sh

requirements:
  host:
    - nodejs >=18
  run:
    - nodejs >=18

tests:
  - package_contents:
      bin:
        - playwright-cli
  - script:
      - playwright-cli --version

about:
  homepage: https://github.com/microsoft/playwright-cli
  repository: https://github.com/microsoft/playwright-cli
  license: Apache-2.0
  license_file: LICENSE
  summary: Playwright command line interface for browser automation from agents and scripts
