context:
  version: "0.1.21"

package:
  name: playwright-cli
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/@playwright/cli/-/cli-${{ version }}.tgz
  sha256: 46d0b66061dd4a84c287e36965fd3f1a8c6a49cbcf3b3f90f842023833d5234c

build:
  number: 0
  script: build.sh

requirements:
  host:
    - nodejs >=18
  run:
    - nodejs >=18

tests:
  - package_contents:
      bin:
        - playwright-cli
  - script:
      - playwright-cli --version

about:
  homepage: https://github.com/microsoft/playwright-cli
  repository: https://github.com/microsoft/playwright-cli
  license: Apache-2.0
  license_file: LICENSE
  summary: Playwright command line interface for browser automation from agents and scripts
