context:
  version: "0.1.1"

package:
  name: pygnuutils
  version: ${{ version }}

source:
  url: https://files.pythonhosted.org/packages/03/20/6a828fe03d6586241b824ee06c7da854ea351716006a62fd2548eaa5710b/pygnuutils-0.1.1.tar.gz
  sha256: 51ab4f27deb59102b7a04192f7585ff2b3a9de03739982f0b19d3cd4d16bea76

build:
  number: 0
  noarch: python
  python:
    entry_points:
      - pygnuutils = pygnuutils.__main__:main
  script: python -m pip install . --no-deps --no-build-isolation -v

requirements:
  host:
    - python 3.13.*
    - pip
    - setuptools >=43.0.0
    - wheel
  run:
    - python >=3.13,<3.14
    - click

tests:
  - python:
      imports:
        - pygnuutils
      python_version: 3.13.*
  - script:
      - pygnuutils --help

about:
  homepage: https://pypi.org/project/pygnuutils/
  license: GPL-3.0-or-later
  license_file: LICENSE
  summary: "A python implementation for GNU utils"
