context:
  name: gtsam
  version: 1.0

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  git: https://github.com/borglab/gtsam.git
  rev: 90f6f33f6c015e4227f927f6af7b356fe0930809
  patches:
    - nobuild-examples-timing.patch

build:
  number: 1
  skip: target_platform != "linux-64"

requirements:
  build:
    - ${{ compiler("c") }}
    - ${{ stdlib("c") }}
    - ${{ compiler("cxx") }}
    - ninja
    - cmake
    - pybind11                               # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - python                                 # [build_platform != target_platform]
  host:
    - python
    - libboost-devel
    - eigen
    - geographiclib-cpp
    - metis
    - suitesparse
    - tbb
    - tbb-devel
    - pybind11
    - pyparsing
    - numpy
    - setuptools
    - pip
  run:
    - python
    - pyparsing
    - numpy

about:
  homepage: https://github.com/borglab/gtsam
  summary: GTSAM is a library of C++ classes that implement smoothing and mapping (SAM) in robotics and vision
  license: BSD-3-Clause
  license_file:
    - LICENSE
    - LICENSE.BSD

extra:
  recipe-maintainers:
    - fontan