context:
  version: "0.2.3"

package:
  name: apple-compress
  version: ${{ version }}

source:
  url: https://files.pythonhosted.org/packages/91/14/cdb0bdb6147a019d2d8a1e144910c6a8d257d0e58f63bbd105bda0fce7dc/apple_compress-0.2.3.tar.gz
  sha256: a1c855cec8bd73210ae9522c53a841ca515ded2f0c9d5b4e728d0d93fee46a29

build:
  number: 0
  skip: target_platform != "osx-arm64"
  python:
    entry_points:
      - acompress = apple_compress.__main__:main
  script: python -m pip install . --no-deps --no-build-isolation -v

requirements:
  host:
    - python 3.13.*
    - pip
    - poetry-core
  run:
    - python >=3.13,<3.14
    - click <9.0.0,>=8.1.7
    - loguru <0.8.0,>=0.7.2

tests:
  - python:
      imports:
        - apple_compress
      python_version: 3.13.*
  - script:
      - acompress --help

about:
  homepage: https://pypi.org/project/apple-compress/
  license: MIT
  license_file: LICENSE
  summary: "Python bindings for Apple's libcompression."
