context:
  version: "0.0.3"

package:
  name: pmd-net-addr
  version: ${{ version }}

source:
  url: https://files.pythonhosted.org/packages/ce/bb/e24ffb9af4243050b54fbaf08393879456f1bd98996b66c6df509106ad2b/pmd_net_addr-0.0.3.tar.gz
  sha256: 1b0fcb3b77f30076237360eb4cf0243483278a2650fd4a194985cc69b1de07e5

build:
  number: 0
  noarch: python
  script: python -m pip install . --no-deps --no-build-isolation -v

requirements:
  host:
    - python 3.13.*
    - pip
    - setuptools >=61.0
  run:
    - python >=3.13,<3.14
    - typing_extensions >=4.6

tests:
  - python:
      imports:
        - pmd_net_addr
      python_version: 3.13.*

about:
  homepage: https://pypi.org/project/pmd-net-addr/
  license: GPL-3.0-or-later
  license_file: LICENSE
  summary: "An alternative to Python's standard-library ipaddress module \u2014 originally built for the PyTCP stack, fully usable on its own."
